language: node_js
node_js:
  - "11.4.0"
  - "11.0.0"
  - "10.14.1"
  - "10.5.0"
  - "10.0.0"
  - "9.11.2"
  - "9.0.0"
  - "8.11.3"
  - "8.0.0"
  - "7.10.1"
  - "7.0.0"
  - "6.14.3"
  - "6.0.0"
script:
  - npm test
